language: r
r:
  - devel
  - release
sudo: FALSE
cache: packages

warnings_are_errors: TRUE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_github_packages:
  - jimhester/covr

# https://docs.travis-ci.com/user/languages/cpp/#gcc-on-linux

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


after_success:
  - travis_wait 59 Rscript -e 'covr::coveralls(line_exclusions="src/init.cpp")'

