language: r
sudo: false
cache:
  - packages
  - ccache

latex: true
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_github_packages:
  - jimhester/covr
  - dmenne/breathtestcore

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check breathteststan*tar.gz

after_script:
  - tar -ztvf breathteststan_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - cat rstanarm.Rcheck/00*
