language: r
r:
  - devel
  - release
sudo: FALSE
cache: packages

warnings_are_errors: TRUE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_github_packages:
  - jimhester/covr

env:
  matrix:
    - CXX_OLEVEL=2 CXX=clang++

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-5.0' ]
          packages:
            - llvm-5.0-dev
      env:
        - CXX_OLEVEL=2 CXX=clang++



after_success:
  - travis_wait 59 Rscript -e 'covr::coveralls(line_exclusions="src/init.cpp")'

