#' @title breathteststan
#' @description Stan fits to 13C breath test curves. This
#'   is an add-on package to package breathtestcore (https://github.com/dmenne/breathtestcore)
#'
#' @docType package

#' @title List of stanmodels
#' @description stanmodel is generated by \code{stanmodels.R} and normally not exported.
#' For easier testing, it is exported here, but this might by a bad idea.
#' Without exporting, access is available via \code{breathteststan:::stanmodels},
#' which is not very nice either.
#' @examples
#' names(stanmodels)
#' @export stanmodels
#' @import rstan
#' @import methods
#' @import dplyr
#' @import breathtestcore
#' @importFrom stats rnorm rlnorm
#' @importFrom Rcpp loadModule
#' @importFrom utils capture.output
#' @importFrom stringr str_extract str_match
#' @importFrom tibble as_tibble
#' @importFrom purrr map_df
#' @importFrom stats na.omit quantile
#' @import rstan
#' @useDynLib breathteststan, .registration = TRUE
